Repository bandprotocol/band, pull requests merged in 2019-08, with the labels that each got.

#64 fix bug
  .circleci/config.yml
  app/src/components/BuySellModal/BuySellModal.js
  app/src/components/BuySellModal/BuySellModalRender.js
  app/src/components/PriceGraph/PriceGraphRender.js
Labels: bandapp, bug

#52 disabled deposit button when remaining token = 0
  app/src/pages/CommunityDataProvider/ProviderListBody.js
  app/src/pages/CommunityDataProvider/ProviderListBodyRender.js
Labels: bandapp, enhancement

#122 remove airdrop nav link
  web/src/components/Navbar.js
Labels: bug

#119 fix whitepaper version on the websiteto 3.1 to 3.0
  web/src/pages/Landing/Landing.js
Labels: bug

#139 Blinking developer page
  web/src/pages/Developer.js
Labels: bandweb, enhancement

#124 change sidebar from multiple tcds to one tcd
  app/src/Routes.js
  app/src/TCDRoutes.js
  app/src/components/MegaCommunityCard.js
  app/src/components/Sidebar/Sidebar.js
  app/src/components/Sidebar/SidebarRender.js
  app/src/utils/tcds.js
Labels: bandapp, enhancement

#160 Improve performance
  app/package-lock.json
  app/package.json
  app/public/index.html
  app/src/App.css
  app/src/TCDRoutes.js
  app/src/components/ApplyIdentityModal/ApplyIdentityModal.js
  app/src/components/ApplyIdentityModal/Result.js
  app/src/components/BecomeProviderModal/BecomeProviderModal.js
  app/src/components/BuySellModal/BuySellModalRender.js
  app/src/components/DataHeader.js
  app/src/components/DataPoint.js
  app/src/components/DepositWithdrawModal/DepositWithdrawModal.js
  app/src/components/ImageUpload.js
  app/src/components/MakeNewRequestModal/Step1.js
  app/src/components/MakeNewRequestModal/Step2.js
  app/src/components/MegaCommunityCard.js
  app/src/components/Navbar/NavbarRender.js
  app/src/components/NewWebRequestModal/Step3.js
  app/src/components/Pagination/PaginationRender.js
  app/src/components/ParticipationStatus/ParticipationStatus.js
  app/src/components/ProposalBox/ProposalBoxRender.js
  app/src/components/ProposalDetail/ProposalDetail.js
  app/src/components/RewardCard/RewardCard.js
  app/src/components/Sidebar/SidebarRender.js
  app/src/components/TransactionPopup.js
  app/src/components/YourVote/YourVote.js
  app/src/components/table/LotteryTable.js
  app/src/components/table/SportTable.js
  app/src/components/table/WebRequestTable.js
  app/src/data/fetcher/IdentityFetcher.js
  app/src/data/fetcher/LotteryFetcher.js
  app/src/data/fetcher/PriceFetcher.js
  app/src/data/fetcher/SportFetcher.js
  app/src/images/background-header.webp
  app/src/pages/Communities/CommunitiesRender.js
  app/src/pages/CommunityDataSet/CommunityDataSetPrice.js
  app/src/pages/CommunityDataSet/CommunityDataSetSport.js
  app/src/pages/CommunityDetail/CommunityDetailRender.js
  app/src/pages/CommunityParameter/CommunityParameterRender.js
  app/src/pages/CommunityProposal/CommunityProposal.js
  app/src/reducers/tcd.js
  app/src/reducers/transaction.js
  app/src/sagas/current.js
  app/src/sagas/index.js
  app/src/sagas/prices.js
  app/src/sagas/proposals.js
  app/src/selectors/dataProvider.js
  app/src/utils/helper.js
Labels: bandapp, enhancement, good first issue

#168 Fix prices fx
  app/src/data/detail/price.js
  app/src/ui/colors.js
Labels: bandapp, bug
